CREATE TABLE SAILPRO.T_BSP(
Production_Date date NOT NULL,
-- BSP
Oven_Push_Mon_CPLY int,
oven_Push_Mon_Tar_APP int,
oven_Push_Mon_Tar_Rev int,
oven_Push_Daily_Tar_APP int,
oven_Push_Daily_Tar_Rev int,
Oven_Push_Act int,
Oven_Push_Cum int,
Oven_Push_MRate int,
Oven_Push_APP_Fulfill int,

Sinter_Mon_CPLY int,
Sinter_Mon_Tar_APP int,
Sinter_Mon_Tar_Rev int,
Sinter_Daily_Tar_APP int,
Sinter_Daily_Tar_Rev int,
Sinter_Act int,
Sinter_Cum int,
Sinter_MRate int,
Sinter_APP_Fulfill int,

HM_Mon_CPLY int,
HM_Mon_Tar_APP int,
HM_Mon_Tar_Rev int,
HM_Daily_Tar_APP int,
HM_Daily_Tar_Rev int,
HM_Act int,
HM_Cum int,
HM_MRate int,
HM_APP_Fulfill int,

PI_Mon_CPLY int,
PI_Mon_Tar_APP int,
PI_Mon_Tar_Rev int,
PI_Daily_Tar_APP int,
PI_Daily_Tar_Rev int,
PI_Act int,
PI_Cum int,
PI_MRate int,
PI_APP_Fulfill int,

CS_Mon_CPLY int,
CS_Mon_Tar_APP int,
CS_Mon_Tar_Rev int,
CS_Daily_Tar_APP int,
CS_Daily_Tar_Rev int,
CS_Act int,
CS_Cum int,
CS_MRate int,
CS_APP_Fulfill int,

SMS_1_Mon_CPLY int,
SMS_1_Mon_Tar_APP int,
SMS_1_Mon_Tar_Rev int,
SMS_1_Daily_Tar_APP int,
SMS_1_Daily_Tar_Rev int,
SMS_1_Act int,
SMS_1_Cum int,
SMS_1_MRate int,
SMS_1_APP_Fulfill int,

SMS_2_CC_Mon_CPLY int,
SMS_2_CC_Mon_Tar_APP int,
SMS_2_CC_Mon_Tar_Rev int,
SMS_2_CC_Daily_Tar_APP int,
SMS_2_CC_Daily_Tar_Rev int,
SMS_2_CC_Act int,
SMS_2_CC_Cum int,
SMS_2_CC_MRate int,
SMS_2_CC_APP_Fulfill int,

BBM_Ingot_Mon_CPLY int,
BBM_Ingot_Mon_Tar_APP int,
BBM_Ingot_Mon_Tar_Rev int,
BBM_Ingot_Daily_Tar_APP int,
BBM_Ingot_Daily_Tar_Rev int,
BBM_Ingot_Act int,
BBM_Ingot_Cum int,
BBM_Ingot_MRate int,
BBM_Ingot_APP_Fulfill int,

Rails_Mon_CPLY int,
Rails_Mon_Tar_APP int,
Rails_Mon_Tar_Rev int,
Rails_Daily_Tar_APP int,
Rails_Daily_Tar_Rev int,
Rails_Act int,
Rails_Cum int,
Rails_MRate int,
Rails_APP_Fulfill int,

URM_Mon_CPLY int,
URM_Mon_Tar_APP int,
URM_Mon_Tar_Rev int,
URM_Daily_Tar_APP int,
URM_Daily_Tar_Rev int,
URM_Act int,
URM_Cum int,
URM_MRate int,
URM_APP_Fulfill int,

MM_Mon_CPLY int,
MM_Mon_Tar_APP int,
MM_Mon_Tar_Rev int,
MM_Daily_Tar_APP int,
MM_Daily_Tar_Rev int,
MM_Act int,
MM_Cum int,
MM_MRate int,
MM_APP_Fulfill int,

WRM_Mon_CPLY int,
WRM_Mon_Tar_APP int,
WRM_Mon_Tar_Rev int,
WRM_Daily_Tar_APP int,
WRM_Daily_Tar_Rev int,
WRM_Act int,
WRM_Cum int,
WRM_MRate int,
WRM_APP_Fulfill int,

Plate_Mill_Mon_CPLY int,
Plate_Mill_Mon_Tar_APP int,
Plate_Mill_Mon_Tar_Rev int,
Plate_Mill_Daily_Tar_APP int,
Plate_Mill_Daily_Tar_Rev int,
Plate_Mill_Act int,
Plate_Mill_Cum int,
Plate_Mill_MRate int,
Plate_Mill_APP_Fulfill int,

Semis_Mon_CPLY int,
Semis_Mon_Tar_APP int,
Semis_Mon_Tar_Rev int,
Semis_Daily_Tar_APP int,
Semis_Daily_Tar_Rev int,
Semis_Act int,
Semis_Cum int,
Semis_MRate int,
Semis_APP_Fulfill int,

Fin_Steel_Mon_CPLY int,
Fin_Steel_Mon_Tar_APP int,
Fin_Steel_Mon_Tar_Rev int,
Fin_Steel_Daily_Tar_APP int,
Fin_Steel_Daily_Tar_Rev int,
Fin_Steel_Act int,
Fin_Steel_Cum int,
Fin_Steel_MRate int,
Fin_Steel_APP_Fulfill int,

SS_Prod_Mon_CPLY int,
SS_Prod_Mon_Tar_APP int,
SS_Prod_Mon_Tar_Rev int,
SS_Prod_Daily_Tar_APP int,
SS_Prod_Daily_Tar_Rev int,
SS_Prod_Act int,
SS_Prod_Cum int,
SS_Prod_MRate int,
SS_Prod_APP_Fulfill int,

SS_Desp_Mon_CPLY int,
SS_Desp_Mon_Tar_APP int,
SS_Desp_Mon_Tar_Rev int,
SS_Desp_Daily_Tar_APP int,
SS_Desp_Daily_Tar_Rev int,
SS_Desp_Act int,
SS_Desp_Cum int,
SS_Desp_MRate int,
SS_Desp_APP_Fulfill int

PRIMARY KEY (Production_Date)  
);


-- CREATE USER 'test_updater'@'localhost' IDENTIFIED BY 'updater123';
GRANT SELECT, INSERT ON SAILPRO.* TO 'test_updater'@'localhost';

-- CREATE USER 'test'@'localhost' IDENTIFIED BY 'test';
GRANT SELECT ON SAILPRO.* TO 'test'@'localhost';


