CREATE TABLE SAILPRO.T_RSP(
Production_Date date NOT NULL,

Oven_Push_Mon_CPLY int,
oven_Push_Mon_Tar_APP int,
oven_Push_Mon_Tar_Rev int,
oven_Push_Daily_Tar_APP int,
oven_Push_Daily_Tar_Rev int,
Oven_Push_Act int,
Oven_Push_Cum int,
Oven_Push_MRate int,
Oven_Push_APP_Fulfill int,

Sinter_Mon_CPLY int,
Sinter_Mon_Tar_APP int,
Sinter_Mon_Tar_Rev int,
Sinter_Daily_Tar_APP int,
Sinter_Daily_Tar_Rev int,
Sinter_Act int,
Sinter_Cum int,
Sinter_MRate int,
Sinter_APP_Fulfill int,

HM_Mon_CPLY int,
HM_Mon_Tar_APP int,
HM_Mon_Tar_Rev int,
HM_Daily_Tar_APP int,
HM_Daily_Tar_Rev int,
HM_Act int,
HM_Cum int,
HM_MRate int,
HM_APP_Fulfill int,

PI_Mon_CPLY int,
PI_Mon_Tar_APP int,
PI_Mon_Tar_Rev int,
PI_Daily_Tar_APP int,
PI_Daily_Tar_Rev int,
PI_Act int,
PI_Cum int,
PI_MRate int,
PI_APP_Fulfill int,

CS_Mon_CPLY int,
CS_Mon_Tar_APP int,
CS_Mon_Tar_Rev int,
CS_Daily_Tar_APP int,
CS_Daily_Tar_Rev int,
CS_Act int,
CS_Cum int,
CS_MRate int,
CS_APP_Fulfill int,

SMS1_CC_Mon_CPLY int,
SMS1_CC_Mon_Tar_APP int,
SMS1_CC_Mon_Tar_Rev int,
SMS1_CC_Daily_Tar_APP int,
SMS1_CC_Daily_Tar_Rev int,
SMS1_CC_Act int,
SMS1_CC_Cum int,
SMS1_CC_MRate int,
SMS1_CC_APP_Fulfill int,

SMS2_CC_Mon_CPLY int,
SMS2_CC_Mon_Tar_APP int,
SMS2_CC_Mon_Tar_Rev int,
SMS2_CC_Daily_Tar_APP int,
SMS2_CC_Daily_Tar_Rev int,
SMS2_CC_Act int,
SMS2_CC_Cum int,
SMS2_CC_MRate int,
SMS2_CC_APP_Fulfill int,

Caster_3_Mon_CPLY int,
Caster_3_Mon_Tar_APP int,
Caster_3_Mon_Tar_Rev int,
Caster_3_Daily_Tar_APP int,
Caster_3_Daily_Tar_Rev int,
Caster_3_Act int,
Caster_3_Cum int,
Caster_3_MRate int,
Caster_3_APP_Fulfill int,

Plate_Mill_Mon_CPLY int,
Plate_Mill_Mon_Tar_APP int,
Plate_Mill_Mon_Tar_Rev int,
Plate_Mill_Daily_Tar_APP int,
Plate_Mill_Daily_Tar_Rev int,
Plate_Mill_Act int,
Plate_Mill_Cum int,
Plate_Mill_MRate int,
Plate_Mill_APP_Fulfill int,

New_PM_Mon_CPLY int,
New_PM_Mon_Tar_APP int,
New_PM_Mon_Tar_Rev int,
New_PM_Daily_Tar_APP int,
New_PM_Daily_Tar_Rev int,
New_PM_Act int,
New_PM_Cum int,
New_PM_MRate int,
New_PM_APP_Fulfill int,

HSM_Mon_CPLY int,
HSM_Mon_Tar_APP int,
HSM_Mon_Tar_Rev int,
HSM_Daily_Tar_APP int,
HSM_Daily_Tar_Rev int,
HSM_Act int,
HSM_Cum int,
HSM_MRate int,
HSM_APP_Fulfill int,

CR_Saleable_Mon_CPLY int,
CR_Saleable_Mon_Tar_APP int,
CR_Saleable_Mon_Tar_Rev int,
CR_Saleable_Daily_Tar_APP int,
CR_Saleable_Daily_Tar_Rev int,
CR_Saleable_Act int,
CR_Saleable_Cum int,
CR_Saleable_MRate int,
CR_Saleable_APP_Fulfill int,

CRNO_Mon_CPLY int,
CRNO_Mon_Tar_APP int,
CRNO_Mon_Tar_Rev int,
CRNO_Daily_Tar_APP int,
CRNO_Daily_Tar_Rev int,
CRNO_Act int,
CRNO_Cum int,
CRNO_MRate int,
CRNO_APP_Fulfill int,

Semis_Mon_CPLY int,
Semis_Mon_Tar_APP int,
Semis_Mon_Tar_Rev int,
Semis_Daily_Tar_APP int,
Semis_Daily_Tar_Rev int,
Semis_Act int,
Semis_Cum int,
Semis_MRate int,
Semis_APP_Fulfill int,

Fin_Steel_Mon_CPLY int,
Fin_Steel_Mon_Tar_APP int,
Fin_Steel_Mon_Tar_Rev int,
Fin_Steel_Daily_Tar_APP int,
Fin_Steel_Daily_Tar_Rev int,
Fin_Steel_Act int,
Fin_Steel_Cum int,
Fin_Steel_MRate int,
Fin_Steel_APP_Fulfill int,

SS_Prod_Mon_CPLY int,
SS_Prod_Mon_Tar_APP int,
SS_Prod_Mon_Tar_Rev int,
SS_Prod_Daily_Tar_APP int,
SS_Prod_Daily_Tar_Rev int,
SS_Prod_Act int,
SS_Prod_Cum int,
SS_Prod_MRate int,
SS_Prod_APP_Fulfill int,

SS_Desp_Mon_CPLY int,
SS_Desp_Mon_Tar_APP int,
SS_Desp_Mon_Tar_Rev int,
SS_Desp_Daily_Tar_APP int,
SS_Desp_Daily_Tar_Rev int,
SS_Desp_Act int,
SS_Desp_Cum int,
SS_Desp_MRate int,
SS_Desp_APP_Fulfill int,

PRIMARY KEY (Production_Date)  
);


-- CREATE USER 'test_updater'@'localhost' IDENTIFIED BY 'updater123';
GRANT SELECT, INSERT ON SAILPRO.* TO 'test_updater'@'localhost';

-- CREATE USER 'test'@'localhost' IDENTIFIED BY 'test';
GRANT SELECT ON SAILPRO.* TO 'test'@'localhost';


